#!/bin/bash

set -ex

# Download Composer as a PHAR file.
curl -o composer.phar https://getcomposer.org/download/1.9.1/composer.phar
chmod +x ./composer.phar

# Install Composer dependencies.
./composer.phar install --no-dev --no-interaction
